---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: image-checker
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: image-checker-sa
          containers:
            - name: image-checker
              image: quay.io/akrugliak/my-alpine-kubectl:latest
              command: ["/bin/sh"]
              args: ["-c", "kubectl get all --all-namespaces -o=jsonpath='{range .items[*]}{.metadata.namespace} {\"\\t\"} { .kind } {\"\\t\"} { .metadata.name } {\"\\t\"} {range .spec.containers[*]}{.image} {end} {\"\\n\"}'"]
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-checker-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-checker-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "replicationcontrollers", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-checker-rolebinding
subjects:
- kind: ServiceAccount
  name: image-checker-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: image-checker-role
  apiGroup: rbac.authorization.k8s.io
